### ISSUE TITLE
Improve streamgraph x-axis labels

### ISSUE THREAD

**Issue by crcastle** [heroku/kafka-demo#17]
The x-axis number changing is a little hard to understand quickly.  I can think of two options to make this clearer... one option is to not animate the x-axis.  Just have the numbers on a static axis go from 0:00 on the right to 0:59 on the left.  No animation of the text.  The other option would be to use the timestamp of the data point instead of the number of seconds since it was added to the chart.  Again no animation of the text.

And another option I just thought of is leaving the animation but adding an x-axis label that says "Seconds Since Message Received".  But if removing some of the animation here significantly reduces CPU load (#16), then I'd rather go with that option.

**Comment by lukekarrys** [comment]
This is what it looks like now (static with no animation)
![screen shot 2016-09-22 at 11 19 27 am](https://cloud.githubusercontent.com/assets/542108/18760567/7f9d3f2a-80b6-11e6-83a0-336488d3460f.png)

**Comment by crcastle** [comment]
i think that looks great.  thanks.
