### ISSUE TITLE
Change the rates that are shown

### ISSUE THREAD

**Issue by crcastle** [heroku/kafka-demo#18]
This one is mostly for me (Chris) to do, but if I change the JSON key, you'll need to update on your end.  I'm not sure what these should be yet; we got some conflicting feedback.  Margaret wanted to see them moving more.  Then other feedback was to make them per second, per minute, and per hour to make it easier to explain.  I think I'm going to go with the latter for now.

**Comment by crcastle** [comment]
@lukekarrys do you need me to change the data in the topics twitter-display reads from for this?  If not, I think this can be closed, yes?

**Comment by lukekarrys** [comment]
@crcastle I'm not seeing the new key for `average per hour` yet
![screen shot 2016-09-22 at 4 57 20 pm](https://cloud.githubusercontent.com/assets/542108/18769869/c29548d4-80e5-11e6-9405-8dd03c8c7598.png)

**Comment by crcastle** [comment]
@lukekarrys I'm adding a property named `avgPer3600Seconds`.  That good for you?

**Comment by lukekarrys** [comment]
👍

**Comment by crcastle** [comment]
@lukekarrys deployed.  the value will be `null` until one hour has passed.
