### ISSUE TITLE
Document color palette switch process

### ISSUE THREAD

**Issue by crcastle** [heroku/kafka-demo#20]

**Comment by crcastle** [comment]
@lukekarrys can you implement this such that there is a `SALESFORCE_THEME` environment variable that controls which theme is used.  If its value is `true`, use the salesforce theme as the index page.  Otherwise (missing or any other value), use the heroku theme as index.

You probably know this, but note that environment variables are strings so you may need to use something like [this](https://github.com/heroku/dreamhouse-disco/blob/master/bin/util.js#L3-L6) to make sure you're interpreting it correctly.

**Comment by crcastle** [comment]
@lukekarrys will this work without rebuilding the app?  Sorry I wasn't clear about this, but I was hoping to allow people to set this env var and restart the process (i.e. not deploy) to see the changed theme.

**Comment by lukekarrys** [comment]
I might be confused about the difference between rebuilding the app and restarting the process.

I just did a test where I went into the Heroku dashboard for the app and added a config variable (which restarts the process I think). Once that was done (it took a minute) then refreshing https://twitter-display.herokuapp.com/ showed the salesforce theme. I also tested removing the config variable and it reverted to the heroku theme (after the process restarted).

Is that what you intended?

**Comment by crcastle** [comment]
Oh yeah, nice!  That's what I was looking for.  Apologies... I should have tested before replying.  I looked at your change in the webpack config and assumed a redeploy was necessary.  Just tested and worked great (hope I didn't step on your toes).
