### ISSUE TITLE
Add more colors to chart color palette

### ISSUE THREAD

**Issue by crcastle** [heroku/kafka-demo#23]
Currently there are four as [defined here](https://github.com/crcastle/twitter-display/blob/master/styles/chart-colors.css).  Can you add two more?  I think I am going to limit the number of keywords shown to five, but it would be good to have an extra just in case.

**Comment by lukekarrys** [comment]
@lynnandtonic I added the necessary code to support up to 6 colors. All this should need now is those colors updated [here for heroku](https://github.com/crcastle/twitter-display/blob/master/styles/chart-colors.css#L5-L6) and [here for salesforce](https://github.com/crcastle/twitter-display/blob/master/styles/chart-colors.css#L13-L14)
