### ISSUE TITLE
Create GitHub Pages explanation page

### ISSUE THREAD

**Issue by crcastle** [heroku/kafka-demo#24]

**Comment by lynnandtonic** [comment]
Pushed initial site to https://github.com/crcastle/twitter-display/tree/gh-pages

TODO:
- [x] Add real app name
- [x] Add links to final demo app and GitHub repo 
- [x] Add final copy
- [x] Add final app diagram (better responsive)
- [x] Figure out if this page needs a different Kafka app diagram (one of the tooltips refers to the "visualization below" _was updated with new copy_

**Comment by lynnandtonic** [comment]
@crcastle @justjenu Regarding final TODO items ^ above, do you know who will be creating the content for this page?

**Comment by crcastle** [comment]
@lynnandtonic I will be creating the copy, and I can update the links and app name.  I think you can assign this to me now, unless you have other items to complete.

**Comment by lynnandtonic** [comment]
@crcastle Ok awesome, thanks! Let me know if you need me to jump back in or need any more help here.
