### ISSUE TITLE
issues with node version 7 and up

### ISSUE THREAD

**Issue by bjersey** [heroku/kafka-demo#32]
this doesn't work with node v7 and up

**Comment by crcastle** [comment]
Thanks for catching that @bjersey.  I'm in the midst of refactoring quite a bit this and the other repos it depends on.  In the meantime, I've [updated the `package.json`](https://github.com/heroku/kafka-demo/commit/3c8218a86dc1ba65edb8bad4fdd2c81eeaa0abea) to be more accurate about which versions of node are supported.
